server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Otimização de entrega de arquivos estáticos
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }

    # Redirecionar todas as rotas não encontradas para o index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy reverso para o Backend (opcional, caso não use docker-compose proxying separado)
    # location /api {
    #     proxy_pass http://backend:3333;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    # }
}
